apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: static
  name: static
spec:
  ports:
  - name: "80"
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: static
  type: NodePort
status:
  loadBalancer: {}
